spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth-service
          uri: 'lb://AUTH-SERVICE'
          predicates:
            - Path=/api/auth/**
  application:
    name: GATEWAY
  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'